import 'dotenv/config';
import { and, eq, isNotNull, isNull } from 'drizzle-orm';
import { createDb, type Db } from './client.js';
import * as t from './schema.js';
import { estimateCost } from '../adapters/llm/pricing.js';

/**
 * One-shot backfill of `agent_runs.cost_usd` for runs recorded before the column
 * existed (it was dropped in migration 0009 and restored in 0010).
 *
 * Deliberately a script and NOT part of a migration: migrations here are
 * generated by drizzle-kit and must not be hand-edited, and pure SQL cannot
 * reach `estimateCost` — inlining the price table in SQL would duplicate it and
 * let the copy rot. Running this is optional; it only matters for a local DB
 * that already has review history, since the seed creates no runs at all.
 *
 * Estimates at TODAY's prices from the stored token counts, so a run whose real
 * cost came from the provider is approximated. Unpriced models yield null and
 * are left NULL, never 0 — "free" and "unknown" must stay distinguishable.
 */
export async function backfillCost(db: Db): Promise<{ updated: number; skipped: number }> {
  const rows = await db
    .select({
      id: t.agentRuns.id,
      model: t.agentRuns.model,
      tokensIn: t.agentRuns.tokensIn,
      tokensOut: t.agentRuns.tokensOut,
    })
    .from(t.agentRuns)
    .where(
      and(
        isNull(t.agentRuns.costUsd),
        isNotNull(t.agentRuns.model),
        eq(t.agentRuns.status, 'done'),
      ),
    );

  let updated = 0;
  let skipped = 0;
  for (const r of rows) {
    const cost = estimateCost(r.model!, r.tokensIn ?? 0, r.tokensOut ?? 0);
    if (cost == null) {
      skipped += 1; // model not in the price book — leave it NULL
      continue;
    }
    await db.update(t.agentRuns).set({ costUsd: cost }).where(eq(t.agentRuns.id, r.id));
    updated += 1;
  }
  return { updated, skipped };
}

// CLI entrypoint
if (import.meta.url === `file://${process.argv[1]}`) {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error('DATABASE_URL is required');
    process.exit(1);
  }
  const handle = createDb(url);
  backfillCost(handle.db)
    .then(async (r) => {
      console.log('✓ backfilled agent_runs.cost_usd', r);
      await handle.close();
      process.exit(0);
    })
    .catch(async (err) => {
      console.error('✗ backfill failed:', err);
      await handle.close();
      process.exit(1);
    });
}
