import type { CSSProperties } from "react";

export const s = {
  header: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  } satisfies CSSProperties,
  title: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  headerActions: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  summary: {
    borderLeft: "3px solid var(--border-strong)",
    paddingLeft: 14,
    margin: "0 0 16px",
    fontSize: 14,
    lineHeight: 1.55,
    color: "var(--text-primary)",
    fontStyle: "italic",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  columns: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 20,
    marginBottom: 16,
  } satisfies CSSProperties,
  columnLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    margin: 0,
    padding: 0,
    listStyle: "none",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  listItem: {
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
  } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderRadius: 6,
    background: "var(--warn-bg, rgba(210,153,34,.12))",
    color: "var(--warn, #d29922)",
    fontSize: 13,
    marginBottom: 14,
  } satisfies CSSProperties,
  sourceRow: (muted: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: muted ? "var(--warn, #d29922)" : "var(--text-secondary)",
  }),
  sourceRef: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
  } satisfies CSSProperties,
  footer: {
    marginTop: 16,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
    display: "flex",
    justifyContent: "space-between",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
