import type { CSSProperties } from "react";

/** Co-located styles for ProjectContextView. */
export const s = {
  page: { padding: "28px 32px", maxWidth: 1200, margin: "0 auto" } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "flex-start", gap: 16, marginBottom: 6 } satisfies CSSProperties,
  heading: { fontSize: 26, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  summary: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    marginBottom: 18,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  truncatedNote: { color: "var(--warn)" } satisfies CSSProperties,
  body: { display: "grid", gridTemplateColumns: "320px 1fr", gap: 20, alignItems: "start" } satisfies CSSProperties,
  sidebar: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    maxHeight: "calc(100vh - 220px)",
    overflow: "auto",
    paddingRight: 4,
  } satisfies CSSProperties,
  folderGroup: { display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  folderLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    padding: "0 8px",
  } satisfies CSSProperties,
  docList: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  docButton: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    textAlign: "left",
    padding: "7px 8px",
    borderRadius: 6,
    border: "1px solid transparent",
    background: active ? "var(--bg-hover)" : "transparent",
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
    fontSize: 13,
    cursor: "pointer",
  }),
  preview: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-surface)",
    minHeight: 300,
  } satisfies CSSProperties,
  previewHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "14px 20px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  previewPath: { fontSize: 13, flex: 1, minWidth: 0 } satisfies CSSProperties,
  previewMeta: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  previewBody: { padding: "18px 20px" } satisfies CSSProperties,
  skeletons: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
} as const;
