import type { CSSProperties } from "react";

/** Co-located styles for ConventionsView. */
export const s = {
  page: { padding: "28px 32px", maxWidth: 1100, margin: "0 auto" } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 16,
    marginBottom: 6,
  } satisfies CSSProperties,
  heading: { fontSize: 26, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  repoName: { color: "var(--accent)", fontWeight: 700 } satisfies CSSProperties,
  subtitle: {
    fontSize: 13,
    color: "var(--text-secondary)",
    marginBottom: 18,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  counters: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    marginBottom: 18,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  counterMeta: { marginLeft: "auto", color: "var(--text-muted)" } satisfies CSSProperties,
  log: {
    margin: 0,
    padding: "10px 14px",
    marginBottom: 18,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 12,
    lineHeight: 1.7,
    color: "var(--text-secondary)",
    maxHeight: 120,
    overflow: "auto",
  } satisfies CSSProperties,
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 20,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  toolbarSpacer: { flex: 1 } satisfies CSSProperties,
  selectionNote: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  listNote: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginBottom: 14,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
} as const;
