// ESLint flat config — @devdigest/api.
//
// Severity encodes STATE, not opinion — the same convention .dependency-cruiser.cjs
// uses: `error` = clean today, `warn` = known violations named in an OUTSTANDING
// comment. Promote a rule to `error` in the commit that clears its last violation.
//
// Not linted: `src/vendor/**` (mirror of the shared contracts — edited at its source),
// `src/db/migrations/**` (generated by drizzle-kit), and `clones/` (repos the indexer
// checks out at runtime, incl. copies of this repo).
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: ['dist/**', 'clones/**', 'src/vendor/**', 'src/db/migrations/**', 'coverage/**'],
  },
  js.configs.recommended,
  tseslint.configs.recommended,
  {
    files: ['**/*.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
    },
  },
  {
    // .dependency-cruiser.cjs is CommonJS by extension — `module`/`require` are
    // globals there, not undefined identifiers.
    files: ['**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { ...globals.node },
    },
  },
);
